project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Connecting theory to data: Introduction to Bayesian statistics for ecologists"
  navbar:
    tools:
      - icon: github
        href: https://github.com/aammd/bayes-ecology-csee2026

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

execute: 
  freeze: true

